from tkinter import *
def click(event):
    global scvalue
    text=event.widget . cget("text")
    print(text)
    if text =="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text=="C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+ text)
        screen.update()
cal_root = Tk() 
# widthxheight
cal_root.geometry("700x550")
cal_root.title("my calculator")
# width,height
cal_root.minsize(300,200)
cal_root.maxsize(1100,950)
priya=Label(text="calculator GUI")
priya.pack()
scvalue=StringVar()
scvalue.set("")
screen=Entry(cal_root, textvar=scvalue,font="lucida 40 bold")
screen.pack(fill=X,ipadx=8 , pady=10,padx=10)
f=Frame(cal_root, bg="violet")
b=Button(f, text="C", font="lucida 25 bold")
b.pack(side=LEFT, padx=14,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="<", font="lucida 25 bold")
b.pack(side=LEFT, padx=13,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="%", font="lucida 25 bold")
b.pack(side=LEFT, padx=13,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="//", font="lucida 25 bold")
b.pack(side=LEFT, padx=13,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="**", font="lucida 25 bold")
b.pack(side=LEFT, padx=13,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="sin", font="lucida 25 bold")
b.pack(side=LEFT, padx=13,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text=",", font="lucida 25 bold")
b.pack(side=LEFT, padx=13,pady=18)
b.bind("<Button-1>" ,click)
f.pack()
f=Frame(cal_root, bg="violet")
b=Button(f, text="^", font="lucida 25 bold")
b.pack(side=LEFT, padx=14,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="1", font="lucida 25 bold")
b.pack(side=LEFT, padx=14,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="2", font="lucida 25 bold")
b.pack(side=LEFT, padx=14,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="3", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="/", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="cos", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="[", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
f.pack()
f=Frame(cal_root, bg="violet")
b=Button(f, text="(", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="4", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="5", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="6", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="*", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="tan", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="]", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
f.pack()
f=Frame(cal_root, bg="violet")
b=Button(f, text=")", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="7", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="8", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="9", font="lucida 25 bold")
b.pack(side=LEFT, padx=17,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="-", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="log", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text=">", font="lucida 25 bold")
b.pack(side=LEFT, padx=16,pady=18)
b.bind("<Button-1>" ,click)
f.pack()
f=Frame(cal_root, bg="violet")
b=Button(f, text="!", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text=".", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="0", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="=", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="+", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="ln", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
b=Button(f, text="INV", font="lucida 25 bold")
b.pack(side=LEFT, padx=15,pady=18)
b.bind("<Button-1>" ,click)
f.pack()
cal_root.mainloop()